apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-cart
  template:
    metadata:
      labels:
        app: ubuntu-cart
    spec:
      containers:
        - name: ubuntu-cart
          image: ubuntu-cart:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password  
          
          
                  
              
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  type: NodePort
  selector:
    app: ubuntu-cart
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082
