apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-catalogue
  template:
    metadata:
      labels:
        app: ubuntu-catalogue
    spec:
      containers:
        - name: ubuntu-catalogue
          image: ubuntu-catalogue:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DATABASE
              value: catalogue
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_PORT
              value: "27017"  
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: catalogue-mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalogue-mongo-secret
                  key:  password
            - name: MONGO_AUTH_SOURCE
              value: catalogue      
          
          resources:
            requests:
              cpu: "250m"      # minimum CPU guaranteed
              memory: "256Mi"  # minimum memory guaranteed
            limits:
              cpu: "500m"      # max CPU this container can use
              memory: "512Mi"  # max memory this container can use

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    app: ubuntu-catalogue
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP     
