apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-catalogue
  template:
    metadata:
      labels:
        app: ubuntu-catalogue
    spec:
      containers:
        - name: ubuntu-catalogue
          image: ubuntu-catalogue:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DB
              value: catalogue
  
            - name: MONGO_HOST
              value: "mongodb"
            - name: MONGO_PORT
              value: "27017"  
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_PASS
          
          resources:
            requests:
              cpu: "250m"      # minimum CPU guaranteed
              memory: "256Mi"  # minimum memory guaranteed
            limits:
              cpu: "500m"      # max CPU this container can use
              memory: "512Mi"  # max memory this container can use

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    app: ubuntu-catalogue
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP     
