apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: user
            port:
              number: 80

      - path: /api/ratings
        pathType: Prefix
        backend:
          service:
            name: ratings
            port:
              number: 80

      - path: /api/catalogue
        pathType: Prefix
        backend:
          service:
            name: catalogue
            port:
              number: 80

      - path: /api/shipping
        pathType: Prefix
        backend:
          service:
            name: shipping
            port:
              number: 80

      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80



