apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:

      # Web / Dispatch
      - path: /api/dispatch
        pathType: Prefix
        backend:
          service:
            name: dispatch
            port:
              number: 80

      # Catalogue
      - path: /api/catalogue
        pathType: Prefix
        backend:
          service:
            name: catalogue
            port:
              number: 80

      # Ratings
      - path: /api/ratings
        pathType: Prefix
        backend:
          service:
            name: ratings
            port:
              number: 80

      # User
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: user
            port:
              number: 80

      # Cart
      - path: /api/cart
        pathType: Prefix
        backend:
          service:
            name: cart
            port:
              number: 80

      # Payment
      - path: /api/payment
        pathType: Prefix
        backend:
          service:
            name: payment
            port:
              number: 80

      # Shipping
      - path: /api/shipping
        pathType: Prefix
        backend:
          service:
            name: shipping
            port:
              number: 80



