apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
  - host: app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80

      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: user
            port:
              number: 80

      - path: /api/cart
        pathType: Prefix
        backend:
          service:
            name: cart
            port:
              number: 80

      - path: /api/catalogue
        pathType: Prefix
        backend:
          service:
            name: catalogue
            port:
              number: 80

      - path: /api/ratings
        pathType: Prefix
        backend:
          service:
            name: ratings
            port:
              number: 80

      - path: /api/payment
        pathType: Prefix
        backend:
          service:
            name: payment
            port:
              number: 80

      - path: /api/dispatch
        pathType: Prefix
        backend:
          service:
            name: dispatch
            port:
              number: 80

      - path: /api/shipping
        pathType: Prefix
        backend:
          service:
            name: shipping
            port:
              number: 80
