apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-shipping
  labels:
    app: ubuntu-shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-shipping
  template:
    metadata:
      labels:
        app: ubuntu-shipping
    spec:
      containers:
        - name: ubuntu-shipping
          image: ubuntu-shipping:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shipping-secret
                  key: password
            - name: MYSQL_DATABASE
              value: "cities"
            - name: MYSQL_USER
              valueFrom:
                  name: shipping-secret
                  key: username
            - name: MYSQL_HOST
              value: "mysql"                    
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    app: ubuntu-shipping
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP     
