apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-web
  labels:
    app: ubuntu-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-web
  template:
    metadata:
      labels:
        app: ubuntu-web
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"   
    spec:
      containers:
        - name: ubuntu-web
          image: ubuntu-web:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CATALOGUE_HOST
              value: catalogue
            - name: USER_HOST
              value: user
            - name: CART_HOST
              value: cart
            - name: SHIPPING_HOST
              value: shipping
            - name: PAYMENT_HOST
              value: payment
            - name: RATINGS_HOST
              value: ratings
            - name: DISPATCH_HOST
              value: dispatch
            
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "jaeger.observability.svc.cluster.local:14250"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_SERVICE_NAME
              value: "web"    
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
 
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: ubuntu-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort   
      
